# Official Python base image
FROM python:3.10-slim AS base

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./InterviewMQ ./InterviewMQ

EXPOSE 8000

# Start the server
CMD ["uvicorn", "InterviewMQ:app", "--host", "0.0.0.0", "--port", "8000"]