# Official Python base image
FROM python:3.10-slim AS base

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

COPY ./src .

CMD ["python", "app.py"]
